# NullOrigin Jekyll Configuration
# Author: aMiscreant
# Email: aMiscreant@protonmail.com
# Site: https://amiscreant.github.io

# -------------------
# Site Settings
# -------------------
title: NullOrigin
email: aMiscreant@protonmail.com
description: >-
  Welcome to NullOrigin, the digital playground for curious Miscreants!
baseurl: "" # Leave blank unless using a subdirectory
url: "https://amiscreant.github.io"
github_username: aMiscreant

# -------------------
# Build Settings
# -------------------
theme: minima
plugins:
  - jekyll-feed

# -------------------
# Markdown Configuration
# -------------------
markdown: kramdown
kramdown:
  input: GFM

# -------------------
# Exclude from Processing
# -------------------
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

# -------------------
# Navigation
# -------------------
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: Arduino
    url: /arduino/
  - title: Projects
    url: /projects/
  - title: Tutorials
    url: /tutorials/

# -------------------
# Collections
# -------------------
collections:
  arduino:
    output: true
  projects:
    output: true
  tutorials:
    output: true