# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. You can create any custom
# variable you would like, and they will be accessible in the templates.

title: PyScriptsHub
email: aMiscreant@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "Welcome to PyScriptsHub, your hub for innovative Python 
  projects and tools! Whether you're into automating tasks, 
  developing games, building secure applications, 
  or experimenting with new technologies, 
  we have a range of resources to help you dive deeper into the world of Python. 
  Explore our collection of scripts, tutorials, and open-source projects, 
  designed for both beginners and advanced coders."
baseurl: "" # Leave blank unless you are using a subdirectory
url: "https://amiscreant.github.io" # Your GitHub Pages URL

github_username: aMiscreant

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM # GitHub-flavored Markdown

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
  - title: Tutorials
    url: /tutorials/

collections:
  projects:
  tutorials:
    output: true
