name: Optimize Images

on:
  push:
    branches:
      - / (root)  # Adjust if your default branch is different

jobs:
  optimize_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Optimize images
        run: python optimize_images.py  # Run your optimization script

      - name: Commit optimized images
        run: |
          git config --local user.name "Your Name"
          git config --local user.email "your-email@example.com"
          git add path/to/your/jekyll/site/assets/images
          git commit -m "Optimize images"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
